import json
import os

case_studies = [
    {
        "id": 1,
        "slug": "real-estate-builder-pune",
        "title": "How Real Estate Builder in Pune Scaled Qualified Lead Flow and Reduced CPL by 75%",
        "meta_title": "Pune Real Estate Lead Generation Case Study | RoasBodhi",
        "meta_description": "How a premium developer in Pune generated 840+ pre-qualified leads in 45 days using custom high-speed landing pages and pre-filtered Meta Lead campaigns.",
        "client_name": "Vilas Developers",
        "client_type": "Premium Residential Builder",
        "industry": "real-estate",
        "city": "Pune",
        "state": "Maharashtra",
        "challenge_short": "High cost-per-lead (CPL) on third-party portals and low-quality broker leads instead of actual home buyers.",
        "challenge_full": "The property developer was launching a premium 2 & 3 BHK housing project in Hinjewadi, Pune. In the highly competitive Pune real estate market, third-party housing aggregator portals were delivering low-quality broker leads, outdated contact numbers, and duplicate profiles while charging steep listing packages. The internal sales team was spending over 70% of their working hours sorting through junk leads and brokers instead of speaking to prospective home buyers who had genuine intent and financial eligibility. The cost per site visit was climbing past Rs. 15,000, and the overall marketing budget was being drained by broad-intent Facebook ads showing layout drawings to unqualified audiences. The lack of proper attribution tracking meant they could not pinpoint which ad sets were driving real site visits and apartment bookings.",
        "solution_short": "Deployed custom Astro landing pages with qualifying question forms and structured Meta Ads funnel.",
        "solution_full": "RoasBodhi implemented a two-part performance marketing system to clean up the leads pipeline and scale qualified traffic. First, we designed and built a dedicated project landing page using the blazing-fast Astro.js framework. This custom landing page loaded in under 0.8 seconds in Hinjewadi's mobile network zones, ensuring zero visitor drop-offs from ad clicks. Instead of presenting generic brochure downloads, the landing page integrated a multi-step pre-qualification form requiring visitors to confirm their home purchase timeline, bank loan eligibility status, and direct WhatsApp contact number. Second, we launched hyper-targeted Meta Ads campaign funnels. Instead of optimization for basic lead form clicks, we utilized custom conversion events targeting prospects who answered all verification steps. We excluded active brokers and real estate agents from the targeting criteria by refining target interests and behaviors. Ad creatives focused on drone views of construction progress, actual carpet area dimensions, and transparent pricing structures rather than generic stock graphics. Lastly, we integrated a real-time WhatsApp webhook that instantly pushed new hot leads to the developer's CRM with automated site visit scheduling links, reducing lead response time to under 90 seconds.",
        "services_used": ["meta-ads", "web-development"],
        "duration": "45 days",
        "results": {
            "roas": "4.2X",
            "leads_per_month": 847,
            "cpl_before": 850,
            "cpl_after": 210,
            "revenue_increase": "180%",
            "ad_spend": 150000,
            "bookings": 14,
            "site_visits": 112
        },
        "client_quote": "RoasBodhi completely revamped our sales pipeline. Under their Pay-After-Seeing guarantee, we got a world-class landing page, and within 45 days, our CPL dropped from ₹850 to under ₹210. We booked 14 units directly from their campaign.",
        "featured_image": "/images/case-studies/cs-1.jpg",
        "gallery": ["/images/case-studies/cs-1-gal1.jpg", "/images/case-studies/cs-1-gal2.jpg"],
        "published_date": "2025-01-15",
        "featured": True
    },
    {
        "id": 2,
        "slug": "jewellery-store-jaipur",
        "title": "How a Bridal Jewellery Store in Jaipur Hijacked Local Search and Scaled Walk-ins",
        "meta_title": "Jaipur Jewellery Retail Marketing Case Study | RoasBodhi",
        "meta_description": "See how a heritage silver and gold jewellery store in Jaipur leveraged GMB optimization and localized Instagram campaigns to scale high-value bridal walk-ins.",
        "client_name": "Rajputana Jewellers",
        "client_type": "Heritage Bridal Showroom",
        "industry": "jewellery",
        "city": "Jaipur",
        "state": "Rajasthan",
        "challenge_short": "Low organic footfall and near-zero visibility on Google Maps for high-intent bridal jewellery searches in Jaipur.",
        "challenge_full": "Located in the bustling Johri Bazar of Jaipur, the heritage jewellery showroom was facing stiff competition from newer mall-based outlets and national retail chains. Despite having exquisite hand-crafted bridal collections, they had low organic footfalls and poor visibility on local search. When tourists or local families searched for 'best bridal gold jewellery in Jaipur' or 'heritage jewellery store Johri Bazar,' competitors dominated the local pack. Their Google Business Profile was unoptimized, lacked high-resolution catalog photos, had no recent customer reviews, and was missing product listings. Additionally, they had never run localized social media campaigns, missing out on targeting NRI families visiting Jaipur for destination wedding shopping.",
        "solution_short": "Engineered a local GMB dominance roadmap and ran localized Instagram catalogue campaigns.",
        "solution_full": "We implemented a dual-action GMB SEO and localized social media campaign to drive store walk-ins. First, we conducted a complete GMB profile overhaul: we updated business categories, added geo-tagged high-res photos of bridal collections, listed key items in the product catalog with pricing ranges, and set up a systematic WhatsApp review-request loop with past buyers. This boosted their ranking into the top 3 spots of Jaipur's maps search. Second, we set up and executed targeted Instagram and Facebook ads using dynamic catalogs. We targeted high-income wedding shoppers in Delhi NCR, Mumbai, and specific circles in Jaipur. The ad creatives featured raw video clips showing the details of heritage Kundan and Polki work. We integrated a call-to-action redirecting prospects to chat directly with the showroom manager on WhatsApp to book a private viewing session. This combined approach bridged digital search intent with direct retail store walk-ins.",
        "services_used": ["meta-ads", "google-my-business"],
        "duration": "60 days",
        "results": {
            "roas": "5.1X",
            "leads_per_month": 120,
            "cpl_before": 1200,
            "cpl_after": 450,
            "revenue_increase": "218%",
            "ad_spend": 230000,
            "walkins": 84,
            "whatsapp_chats": 410
        },
        "client_quote": "Our heritage showroom saw a massive surge in walk-ins during the wedding season. Families from Delhi NCR and Mumbai showed us Instagram ads on their phones. Our Google Maps listings now bring daily inquiries.",
        "featured_image": "/images/case-studies/cs-2.jpg",
        "gallery": ["/images/case-studies/cs-2-gal1.jpg", "/images/case-studies/cs-2-gal2.jpg"],
        "published_date": "2025-02-10",
        "featured": True
    },
    {
        "id": 3,
        "slug": "dental-clinic-lucknow",
        "title": "How a Dental Clinic Chain in Lucknow Filled Its Implants Calendar via Local PPC Maps SEO",
        "meta_title": "Lucknow Dental PPC & Local SEO Case Study | RoasBodhi",
        "meta_description": "How a multi-specialty dental clinic in Lucknow achieved 320+ premium treatment bookings and reduced acquisition costs via Google Maps and localized Search Ads.",
        "client_name": "Bodhi Dental Care",
        "client_type": "Multi-Specialty Clinic",
        "industry": "dental-clinics",
        "city": "Lucknow",
        "state": "Uttar Pradesh",
        "challenge_short": "Struggling to acquire high-value dental implant and root canal cases locally, losing to older established clinics.",
        "challenge_full": "The client, a modern dental clinic chain with three branches in Lucknow (Hazratganj, Gomti Nagar, and Aliganj), was struggling to get local bookings for high-value treatments like dental implants, invisible aligners, and cosmetic smile designs. Patients seeking routine checks went to local neighborhood dentists, while premium cosmetic cases were captured by older, established clinics. The client's website was slow, had poor conversion rates, and ranked on page three of Google Search for specialized dental services. Their active Google Ads campaigns were spending Rs. 650 per lead on broad keywords like 'dentist near me,' which mostly brought low-value cavity check inquiries rather than high-value cosmetic consults.",
        "solution_short": "Configured local Google search ads campaigns targeting specific treatment keywords and GMB ranking packs.",
        "solution_full": "RoasBodhi implemented a highly focused local SEO and Google Ads strategy. We began by building optimized landing pages for each specialized treatment (Implants, Aligners, and Root Canals). Each page loaded in under 0.9 seconds and featured interactive smile transformations, surgeon credentials, patient video reviews, and a transparent pricing table. We restructured their Google Ads campaign: we stopped bid groups on broad phrases and targeted exact-match keywords such as 'best dental implants Lucknow' or 'invisible aligners Gomti Nagar.' We launched localized local search ads directly on Google Maps, displaying their Hazratganj and Gomti Nagar branches right at the top when users searched for specialized clinics nearby. To build immediate trust, we set up an automated GMB feedback system that collected post-treatment 5-star ratings, boosting overall trust signals.",
        "services_used": ["google-ads", "google-my-business"],
        "duration": "30 days",
        "results": {
            "roas": "3.8X",
            "leads_per_month": 320,
            "cpl_before": 650,
            "cpl_after": 320,
            "revenue_increase": "145%",
            "ad_spend": 120000,
            "bookings": 92,
            "reviews_added": 75
        },
        "client_quote": "Our treatment chairs are now fully booked. RoasBodhi helped us target premium dental implant patients instead of broad, low-value cavity leads. The transparent local pricing structure did wonders for patient trust.",
        "featured_image": "/images/case-studies/cs-3.jpg",
        "gallery": ["/images/case-studies/cs-3-gal1.jpg", "/images/case-studies/cs-3-gal2.jpg"],
        "published_date": "2025-03-01",
        "featured": True
    },
    {
        "id": 4,
        "slug": "textile-manufacturing-coimbatore",
        "title": "How a Textile Manufacturer in Coimbatore Scaled B2B Export Inquiries by 120%",
        "meta_title": "Coimbatore Textile B2B Lead Generation Case Study | RoasBodhi",
        "meta_description": "Discover how a cotton yarn manufacturer in Coimbatore generated high-intent global bulk export inquiries using Google Ads and custom landing pages.",
        "client_name": "Kovai Cotton Mills",
        "client_type": "Cotton Yarn & Fabric Manufacturer",
        "industry": "manufacturing",
        "city": "Coimbatore",
        "state": "Tamil Nadu",
        "challenge_short": "Low digital B2B inquiry flow, depending entirely on traditional brokers and local trade exhibitions.",
        "challenge_full": "This B2B textile manufacturer in Coimbatore was dependent on traditional brokers, local trade exhibitions, and outdated catalogs to secure bulk orders for cotton yarn and fabrics. With the emergence of global online trade, broker margins were rising, while domestic bulk order volumes were fluctuating. The client lacked a professional digital catalog, and their existing company website was an old HTML page that didn't describe product specifications, yarn count details, or bulk ordering quantities. They had zero search visibility for B2B export buyer searches, missing out on direct bulk purchasing inquiries from apparel exporters in India and abroad.",
        "solution_short": "Built a structured B2B catalogue landing page and launched targeted Google Search ads.",
        "solution_full": "We designed and launched a structured B2B catalog landing page outlining fabric specifications, yarn counts, certifications, and manufacturing capacity. We optimized the landing page layout with clear calls-to-action for 'Request Bulk Quote' and 'Download Technical Catalogue.' Next, we launched Google Search Ads targeting commercial search queries such as 'cotton fabric manufacturers Coimbatore' and 'wholesale yarn suppliers India.' We excluded consumer searches ('retail cotton shops') by adding negative keywords. We ran campaigns targeting apparel export hubs like Tirupur, Ahmedabad, and Ludhiana to capture direct wholesale buyers. An integrated inquiry form automatically routed wholesale inquiries to the sales head on WhatsApp.",
        "services_used": ["google-ads", "web-development"],
        "duration": "60 days",
        "results": {
            "roas": "3.0X",
            "leads_per_month": 150,
            "cpl_before": 500,
            "cpl_after": 250,
            "revenue_increase": "120%",
            "ad_spend": 80000,
            "bulk_deals": 9,
            "export_inquiries": 42
        },
        "client_quote": "We bypass broker commissions by getting wholesale buyers directly via Google. The B2B catalogue designed by RoasBodhi loads instantly on mobile and has transformed our sales approach.",
        "featured_image": "/images/case-studies/cs-4.jpg",
        "gallery": ["/images/case-studies/cs-4-gal1.jpg"],
        "published_date": "2025-03-25",
        "featured": False
    },
    {
        "id": 5,
        "slug": "ceramic-export-morbi",
        "title": "How a Ceramic Tiles Exporter in Morbi Secured Global Buyers via Multi-lingual Google Ads",
        "meta_title": "Morbi Ceramic Tiles Export Marketing Case Study | RoasBodhi",
        "meta_description": "Case study of a Morbi-based ceramic tile factory scaling B2B inquiries from Middle East and European buyers via global Google PPC.",
        "client_name": "Morbi Ceramic Hub",
        "client_type": "Ceramic & Vitrified Tiles Exporter",
        "industry": "manufacturing",
        "city": "Morbi",
        "state": "Gujarat",
        "challenge_short": "Low digital B2B export leads and heavy reliance on local commission agents for global deals.",
        "challenge_full": "Morbi accounts for a huge chunk of India's ceramic tile production, but local manufacturers are heavily reliant on commission agents and export aggregators to secure global buyers. This client was struggling to get direct export deals from distributors and builders in the Middle East, East Africa, and Eastern Europe. Their website had poor loading speeds, was not optimized for mobile devices, and lacked detailed catalog specifications. Agents took a significant cut of every export container, shrinking the manufacturer's net profit margins. The client needed a direct path to overseas commercial buyers and large-scale real estate developers.",
        "solution_short": "Built high-speed mobile-first catalogue landing pages and launched global B2B Google Ads campaigns.",
        "solution_full": "We set up optimized mobile-first landing pages showcasing tile collections, strength test reports, packing metrics, and export container capacities. We built multi-lingual Google Search campaigns targeting wholesale tile buyers in the UAE, Saudi Arabia, Oman, Kenya, and Poland. We targeted intent terms like 'vitrified tiles factory Morbi,' 'ceramic tile suppliers India,' and 'porcelain tiles manufacturer.' By using smart bidding strategies and localized landing pages, we captured direct inquiries from international wholesale distributors, hotel developers, and construction firms, bypass wholesale broker layers.",
        "services_used": ["google-ads", "web-development"],
        "duration": "60 days",
        "results": {
            "roas": "3.4X",
            "leads_per_month": 190,
            "cpl_before": 500,
            "cpl_after": 250,
            "revenue_increase": "145%",
            "ad_spend": 90000,
            "containers_shipped": 18,
            "direct_clients": 6
        },
        "client_quote": "Direct export deals are the key to high margins in Morbi. RoasBodhi helped us secure export containers directly from builders in the UAE and Saudi Arabia without paying middleman fees.",
        "featured_image": "/images/case-studies/cs-5.jpg",
        "gallery": ["/images/case-studies/cs-5-gal1.jpg"],
        "published_date": "2025-04-05",
        "featured": False
    },
    {
        "id": 6,
        "slug": "packers-movers-noida",
        "title": "How a Packers & Movers Agency in Noida Reduced Cost Per Lead by 50% via Local Google PPC",
        "meta_title": "Noida Packers & Movers PPC Case Study | RoasBodhi",
        "meta_description": "See how a packers and movers service provider in Noida optimized their Google Search Ads to cut CPL and scale local household bookings.",
        "client_name": "Namaste Logistics",
        "client_type": "Local & Inter-city Movers",
        "industry": "packers-movers",
        "city": "Noida",
        "state": "Uttar Pradesh",
        "challenge_short": "Low digital inquiry flow and extremely high Google CPC bidding costs due to competitive spam ads.",
        "challenge_full": "The packers and movers industry in Noida is highly competitive, with high CPC rates on Google Ads. The client was paying over Rs. 150 per click on Google search, but half of the clicks went to fake competitors clicking on their ads, and the other half landed on a slow website that failed to convert. Their booking conversion rate was under 3%, resulting in an acquisition cost (CPA) of Rs. 1,800 per client—almost equal to their local moving profit margins. They needed to block invalid clicks, increase website conversion rates, and book local and inter-city moves at lower costs.",
        "solution_short": "Configured invalid click exclusions and deployed a mobile-first quick quote calculator landing page.",
        "solution_full": "We built a mobile-first single-page website with a 'Quick Quote Calculator' that estimated relocation costs in under 3 clicks. This boosted lead conversions from 3% to 18%. Next, we restructured their Google Ads campaign: we targeted exact-match keywords ('packers and movers Noida,' 'house shifting Noida') and set up IP exclusion filters to block competitor click farms. We scheduled campaigns to run during business hours when users make shifting calls. Direct calls and WhatsApp buttons were pinned to the top of the mobile layout, speeding up the contact path for users looking to book a move immediately.",
        "services_used": ["google-ads", "web-development"],
        "duration": "60 days",
        "results": {
            "roas": "3.8X",
            "leads_per_month": 230,
            "cpl_before": 500,
            "cpl_after": 250,
            "revenue_increase": "170%",
            "ad_spend": 50000,
            "bookings_made": 74,
            "cpa_reduction": "52%"
        },
        "client_quote": "Our packers and movers lead generation cost dropped by half in 60 days. The quick quote calculator page built by RoasBodhi converts searchers into customers instantly.",
        "featured_image": "/images/case-studies/cs-6.jpg",
        "gallery": ["/images/case-studies/cs-6-gal1.jpg"],
        "published_date": "2025-04-20",
        "featured": False
    }
]

with open("src/data/case-studies.json", "w", encoding="utf-8") as f:
    json.dump(case_studies, f, indent=2, ensure_ascii=False)

print("case-studies.json updated successfully with 6 unique, comprehensive cases!")
